### ISSUE TITLE
[bug] Issue with player targeting and mouseover

### ISSUE THREAD

**Issue by natinusala** [Phanx/AnyFavoriteMount#10] opened 2016-11-29 21:19 UTC
Hello,

This addon is great, however it randomly prevents me from doing a combat rez, as weird as it sounds. I've got a mouseover macro that I use on the player's name in the group/raid players list on the left.

From times to times, I can't use the macro, saying that "i have no target". When I try to click on the player to actually target him, it says that "the addon has attempted to use a forbidden function" (rough translation as my game is in french).

If you want some more detailled logs (like what is the conflicting function), tell me how to get them and I'll grab them as soon as the bug comes again.

Thanks !

**Comment by natinusala** [comment] 2016-12-04 20:15
It happened again. Please fix this, not being able to crez in a raid because of this addon is not tolerable

**Comment by Phanx** [comment] 2016-12-05 02:20
What is the macro you use? What raid frames are you using (default UI, Grid, Pitbull, VuhDo, etc)? What is the error message you get? (I'd suggest installing an error-catching addon like Bugger or BugSack so you can copy/paste the error message along with some useful debugging information.) Does the problem happen when all other addons are disabled?

Generally speaking, I don't see how this particular problem can be caused by AFM, as it doesn't do anything that could interfere with targeting someone via unit frames, and addons cannot affect (or even detect) the spell targeting mechanic at all, but without more details there's not even anything for me to look into.

**Comment by natinusala** [comment] 2016-12-05 09:52
Thanks for answering,

I use a simple `/cast [@mouseover] The Spell`, with the default frames. The only message I got is a "AFM tried to execute a function reserved to the Blizzard UI", with Disable and Ignore buttons. It happens when I try to target someone (it affects the mouse over too) using the frames. Reloading the UI fixes the issue until next time.

I'll install a debugging add-on and let you know.

**Comment by natinusala** [comment] 2016-12-05 16:47
```
1x [ADDON_ACTION_BLOCKED] L'AddOn 'AnyFavoriteMount' a tenté d'appeler la fonction protégée 'CompactRaidFrame1:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `ClearAllPoints'
FrameXML\FlowContainer.lua:157: in function `FlowContainer_DoLayout'
FrameXML\FlowContainer.lua:17: in function `FlowContainer_ResumeUpdates'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185: in function `CompactRaidFrameContainer_LayoutFrames'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:

```

**Comment by natinusala** [comment] 2016-12-05 17:49
```
1x [ADDON_ACTION_BLOCKED] L'AddOn 'AnyFavoriteMount' a tenté d'appeler la fonction protégée 'CompactRaidFrame2:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:339: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:280: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:115: in function <FrameXML\CompactUnitFrame.lua:51>

Locals:

```

**Comment by Phanx** [comment] 2018-03-04 17:31
Closing this, as AFM will no longer be maintained. The default UI no longer blocks class/profession mounts from being set as favorites, so the primary purpose of AFM no longer exists. The custom random mount selection logic has been merged into my other mount addon [MountMe](https://github.com/phanx-wow/MountMe).

**Closed as completed by Phanx** 2018-03-04 17:31 UTC
